simul/crtools/urls.py
from django.urls import path

from . import views

app_name="crtools"
urlpatterns = [
    # ex: /polls/
    path('timetable/', views.tt_admin_full, name='crtools_tt'),
    path('?p4?admintt/', views.tt_admin, name='cr_tt'),
    path('?p5?adminrem/', views.rem_admin, name='cr_rem'),
    path('reminders/', views.rem_admin_full, name='crtools_rem'),
    
]

simul/home/urls.py
from django.urls import path
from . import views

app_name="home"
urlpatterns = [
    # ex: /polls/
    path('', views.display_home, name='homepage'),
    path('login/',views.login_custom ,name='login'),
]

simul/simul/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('',include('home.urls')),
    path('dashboard/',include('timetable.urls')),
    path('crtools/',include('crtools.urls')),
    path('teacher/',include('teacher.urls')),
    path('admin/', admin.site.urls),
]

simul/timetable/urls.py
from django.urls import path

from . import views

app_name="timetable"
urlpatterns = [
    # ex: /polls/
    path('', views.db_home_full, name='dashboard_home'),
    path('?p1?home/', views.db_home, name='db_home'),
    path('timetable/', views.db_tt_full, name='dashboard_tt'),
    path('?p2?tt/', views.db_tt, name='db_tt'),
    path('attendance/', views.db_attend_full, name='dashboard_attend'),
    path('?p3?att/', views.db_attend, name='db_attend'),    

]

simul/crtools/models.py
from django.db import models
from timetable.models import Course
# Create your models here.


class Reminder(models.Model):
    creation_date=models.DateTimeField()
    set_date=models.DateTimeField()
    reminder_text=models.TextField()

class Notif(models.Model):
    creation_time=models.DateTimeField()
    message=models.TextField()

class TTChange(models.Model):
    course_code=models.ForeignKey(Course,on_delete=models.CASCADE)
    start_hour=models.IntegerField(default=0)
    date=models.DateTimeField()
    deleted=models.BooleanField(default=False)
    lab_hour=models.BooleanField(default=False)

simul/crtools/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
import datetime
from .models import Reminder, TTChange
from timetable.models import TTFormat,Course
# Create your views here.


def tt_admin_full(request):
    username=request.session.get('username')
    userid=request.session.get('userid')
    if userid is None:
        return redirect(reverse('home:homepage'))
    context={
        'username':username,
    }
    return render(request, 'crtools/ttadmin_full.html',context)

def tt_admin(request):
    today_date=datetime.datetime.now().date().strftime('%Y-%m-%d')
    context={ 'ttdate':today_date,'today_set':today_date }


    weekday_today=datetime.datetime.strptime(context['ttdate'],"%Y-%m-%d")
    weekday_today=weekday_today.date().weekday()+1
    
    original_tt=TTFormat.objects.filter(day=weekday_today).order_by('start_hour')
    changes_tt=TTChange.objects.filter(date=context['ttdate']).order_by('start_hour','-date')
    

    merged_tt=[]
    for k in range(1,9):
        org=None
        ch=None
        for o in original_tt:
            if o.start_hour==k:
                org=o
                break
        for c in changes_tt:
            if c.start_hour==k:
                ch=c
                break
        if org and ch :
            if not ch.deleted:
                merged_tt.append(ch)
        if org and not ch:
            merged_tt.append(org)
        if ch and not org:
            merged_tt.append(ch)
    context['day_class']=list(merged_tt)

    if request.method=="POST":
        
        context['ttdate']=request.POST['ttdate']
        
        weekday_today=datetime.datetime.strptime(context['ttdate'],"%Y-%m-%d")
        weekday_today=weekday_today.date().weekday()+1
    
        if weekday_today>5:
            context['errortext']="Please select only a weekday"
            return render(request, 'crtools/tt_admin.html',context)

        

        if 'can_sel' in request.POST:
            context['can']=True
        
        if 'add_sel' in request.POST:
            context['add']=True
        
        courses=Course.objects.filter(course_semester=request.session.get('sem'))
        context['courses']=courses

        if 'canclass' in request.POST:
            for c in merged_tt:
                if c.course_code.course_code == request.POST['class_select']:
                    reference=c
            change=TTChange()
            change.course_code=reference.course_code
            change.start_hour=reference.start_hour
            change.date=datetime.datetime.now().date()
            change.deleted=True
            change.lab_hour=reference.lab_hour
            change.save()

        if 'conchange' in request.POST:
            cc=request.POST['course_add_sel']
            print(cc)
            reference=Course.objects.get(course_code=cc)
            print(reference)
            change2=TTChange()
            change2.course_code=reference
            change2.start_hour=request.POST['hour_add_sel']
            change2.date=datetime.datetime.now().date()
            change2.deleted=False
            if request.POST.get('labconfadd')==True:
                change2.lab_hour=True
            else:
                change2.lab_hour=False
            change2.save()
        
        if 'canchange' in request.POST:
            context['can']=False
            context['add']=False
            context['rep']=False

    
            
            original_tt=TTFormat.objects.filter(day=weekday_today).order_by('start_hour')
            changes_tt=TTChange.objects.filter(date=request.POST['ttdate']).order_by('start_hour','-date')


            merged_tt=[]
            for k in range(1,9):
                org=None
                ch=None
                for o in original_tt:
                    if o.start_hour==k:
                        org=o
                        break
                for c in changes_tt:
                    if c.start_hour==k:
                        ch=c
                        break
                if org and ch :
                    if not ch.deleted:
                        merged_tt.append(ch)
                if org and not ch:
                    merged_tt.append(org)
                if ch and not org:
                    merged_tt.append(ch)
            context['day_class']=list(merged_tt)

    

    return render(request, 'crtools/tt_admin.html',context)

def rem_admin(request):
    today_date=datetime.datetime.now().date().strftime('%Y-%m-%d')
    context={ 'seldate':today_date }
    if request.method=="POST":
        context['seldate']=request.POST['seldate']

        if 'viewr' in request.POST:
            context['view_rem']=True
            reminder_list=Reminder.objects.filter(set_date=request.POST['seldate']).order_by('-creation_date')
            context['rl']=reminder_list

        if 'rem_del' in request.POST:
            context['view_rem']=True
            del_id=request.POST['rem_del']
            Reminder.objects.get(id=del_id).delete()
            context['rl']=Reminder.objects.filter(set_date=request.POST['seldate']).order_by('-creation_date')
            context['view_rem']=True

        if 'addrem' in request.POST:
            context['addrem']=True   

        if "rem_can" in request.POST:
            context['view_rem']=True
        
        if "rem_con" in request.POST:
            new_rem=Reminder()
            new_rem.creation_date=datetime.datetime.now()
            new_rem.set_date=request.POST['seldate']
            new_rem.reminder_text=request.POST['rem_text_stuff']
            new_rem.save()
            context['rl']=Reminder.objects.filter(set_date=request.POST['seldate']).order_by('-creation_date')
            context['view_rem']=True

    return render(request, 'crtools/rem_admin.html',context)

def rem_admin_full(request):
    username=request.session.get('username')
    userid=request.session.get('userid')
    if userid is None:
        return redirect(reverse('home:homepage'))
    context={
        'username':username,
    }         
    
    return render(request, 'crtools/reminders_full.html',context)

simul/crtools/templates/crtools/rem_admin.html
{% load static %}
<html>
<head>
<style>
        @import url('https://fonts.googleapis.com/css?family=Open+Sans|Voltaire');
</style>

<link href="{% static 'timetable/css/subscroll.css' %}" rel="stylesheet">
<link href="{% static 'timetable/css/iframe_style.css' %}" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'home/css/bootstrap.min.css' %}">

</head>
<body  onload="date_setter" style="background-image: url({% static 'home/img/fav.png' %});">
<form method="POST">
    {% csrf_token %}
<table id="tt_admin_table">
    <tr>
        <td colspan="2">
                <br>
        <label>Select Date</label><input type="date" name="seldate" value={{ seldate }}>
        </td>
    </tr>
    <tr>
        <td>
                <br>
            <button name="viewr" value="viewr"> View Reminders </button>
        </td>
        <td>
                <br>
            <button name="addrem" value="addrem"> Add Reminder</button>
        </td>
    </tr>
    {% if view_rem %}
    <tr >
        <td colspan="2">
            <label>Reminders:</label>
            <div id="view_rem">
                {% for rem in rl %}
                <div class="rem_div">
                    <hr>
                    {{ rem.reminder_text }} 
                    <br>
                    <button name="rem_del" value={{rem.id }}>Delete Reminder</button>
                    <hr>
                </div>
                {% endfor %}
            </div>
        </td>
    </tr>
    {% endif %}
    {% if addrem %}
    <tr id="add_rem" >
            <td colspan="2"> 
                    <br>
                <label>Type Reminder text here:</label><br>
                <textarea id="rem_text" name="rem_text_stuff"></textarea>
            </td>
        </tr>
        <tr>
            
            <td>
                <br>
                <button name="rem_con">Confirm</button>
                </td>
                <td>
                        <br>
                <button name="rem_can">Cancel</button>
            </td>
        </tr>
    {% endif %}
</table>    
</form>
</body>
<script src="{% static 'crtools/js/tt_admin.js' %}"></script>
</html>

simul/crtools/templates/crtools/reminders_full.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <link rel="icon" type="image/ico" href="{% static 'home/img/fav.ico' %}"/>
  <style>
    @import url('https://fonts.googleapis.com/css?family=Open+Sans|Voltaire');
  </style>
  <title> Dashboard | Simul </title>

  <!-- Page level plugin CSS-->
  <link href="{% static 'timetable/vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'timetable/css/sb-admin.css' %}" rel="stylesheet">
  <link href="{% static 'timetable/css/scroll.css' %}" rel="stylesheet">

  <!--Iframe resizer-->



</head>

<body id="page-top">

  <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
    <a class="navbar-brand mr-1" href="{% url 'timetable:dashboard_home' %}"><div><img id="logoimg" src="{% static 'timetable/img/dblogo.png'%}" height="80px"></a>
    <!-- Navbar -->
    <div id="long_nav_side">
    <ul class="navbar-nav ml-auto ml-md-0">
      
      <li id="user_greet">Hello {{ username }}!</li>
      
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="icon_rep_med" src="{% static 'home/img/bell.png' %}">
          <span class="badge badge-danger">1</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
          <a class="dropdown-item notifier" href="#" aria-disabled="true">notif 1</a>
          <a class="dropdown-item notifier" href="#"  aria-disabled="true">notif 2</a>
          <a class="dropdown-item notifier" href="#"  aria-disabled="true">notif 3</a>
        </div>
      </li>
      
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="icon_rep_med" src="{% static 'home/img/user.png' %}">
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
        </div>
      </li>

    </ul>
  </div>
  </nav>

  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
      
      <li class="nav-item">
        <a class="nav-link" href="{% url 'timetable:dashboard_home' %}">
            <img class="icon_rep_med" src="{% static 'home/img/dash.png' %}">
          <span>Dashboard</span>
        </a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" >
            <img class="icon_rep_med" src="{% static 'home/img/activity.png' %}" >
          
            <span >Activity Center</span>
          <img class="icon_rep_small" id="down_arrow" src="{% static 'home/img/down.png' %}" >
        </a>
        <div class="dropdown-menu" aria-labelledby="pagesDropdown">
          <h6 class="dropdown-header">ACTIONS</h6>
          <a class="dropdown-item" href="{% url 'timetable:dashboard_tt' %}" >Timetable</a>
          <a class="dropdown-item" href="{% url 'timetable:dashboard_attend' %}" >Attendance Manager</a>
          <div class="dropdown-divider"></div>
          <h6 class="dropdown-header">CR TOOLS</h6>
          <a class="dropdown-item " href="{% url 'crtools:crtools_tt' %}">Timetable Admin</a>
          <a class="dropdown-item active" href="{% url 'crtools:crtools_rem' %}">Reminders Admin</a>
        </div>
      </li>
    </ul>

    <div id="content-wrapper">

      <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'timetable:dashboard_home' %}">Dashboard</a>
          </li>
          <li class="breadcrumb-item active">Reminders-Admin</li>
        </ol>

        <!-- Page Content -->
        <h1>Create & Delete Reminders</h1>
        <hr>
        <div class="resp-container">
            <iframe class="resp-iframe" id="iframe_cr_rem" src ="{%  url 'crtools:cr_rem' %}">
                Why don't you upgrade to a newer browser?
            </iframe>
          </div>
      </div>
      <!-- /.container-fluid -->

      <!-- Sticky Footer -->
      <footer class="sticky-footer">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Simul-HCI Assignment 2019</span>
          </div>
        </div>
      </footer>

    </div>
    <!-- /.content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
      <img class="icon_rep_med" src="{% static 'home/img/top.png' %}">
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'home:homepage' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'timetable/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'timetable/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'timetable/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'timetable/js/sb-admin.min.js' %}"></script>
  <script src="{% static 'timetable/js/iframe_changer.js' %}"></script>

</body>

</html>

simul/crtools/templates/crtools/tt_admin.html
{% load static %}
<html>
<head>
<style>
        @import url('https://fonts.googleapis.com/css?family=Open+Sans|Voltaire');
</style>

<script src="{% static 'crtools/js/tt_admin.js' %}"></script>
<link href="{% static 'timetable/css/subscroll.css' %}" rel="stylesheet">
<link href="{% static 'timetable/css/iframe_style.css' %}" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'home/css/bootstrap.min.css' %}">

</head>
<body style="background-image: url({% static 'home/img/fav.png' %});">
<form method="POST">
    {% csrf_token %}
<table id="tt_admin_table_1">
    <tr>
        <td colspan="3">
            <h4 style="color: rgba(156, 19, 19, 0.836)"> {{ errortext }} </h4>
        </td>
    </tr>
    <tr>
        <td colspan="3">
            <br>
        <label>Select Date: </label><input type="date" name="ttdate" min={{ today_set }} value={{ ttdate }}>
        </td>
    </tr>
    <tr>
        <td>
                    <br>
                    <button name="can_sel"> Cancel Class </button>
        </td>
        <td>
                <h5>(to Replace a class, cancel and add replacement)</h5>
        </td>
        <td>
                <br>
                <button name="add_sel"> Add Class </button>
        </td>
    </tr>
    {% if add %}
    <tr>
            <td colspan="2">
                <br>
                <label>Select Class</label>
                <select name="course_add_sel">
                    {% for course in courses %}
                    <option value= {{ course.course_code }}> {{ course.course_name }}</option>
                    {% endfor %}
                </select>
                <br>
                <input type="checkbox" name="labconfadd" value="True"> Lab Hour<br>
            </td>
            <td>
                <br>
                <label>Select Hour</label>
                <select name="hour_add_sel">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="6">6</option>
                    <option value="7">7</option>
                    <option value="8">8</option>
                </select>
            </td>
            
        </tr>
    {% endif %}
    {% if can %}
    <tr>
        <td colspan="3">
            <br>
            <label>Select Class</label>
            <select name="class_select">
                {% for c in day_class %}
                <option value= {{ c.course_code.course_code }}  > {{ c.course_code.course_name }} {% if c.lab_hour %} - LAB {% endif %}</option>
                {% endfor %}
            </select>

        </td>
        
    </tr>
    {% endif %}
    {% if can %}
    <tr>
        <td colspan="3">
            <br> 
            <button name="canclass">Cancel This Class</button>
            
        </td>
    </tr>
    {% endif %}
    {% if add %}
    <tr>
        <td >
            <br>
            <button name="conchange">Confirm</button>
        </td>
        <td></td>
        <td>
            <br>
            <button name="canchange">Cancel</button>
        </td>
    </tr>
    {% endif %}
</table>    
</form>
</body>

</html>

simul/crtools/templates/crtools/ttadmin_full.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <link rel="icon" type="image/ico" href="{% static 'home/img/fav.ico' %}"/>
  <style>
    @import url('https://fonts.googleapis.com/css?family=Open+Sans|Voltaire');
  </style>
  <title> Dashboard | Simul </title>

  <!-- Page level plugin CSS-->
  <link href="{% static 'timetable/vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'timetable/css/sb-admin.css' %}" rel="stylesheet">
  <link href="{% static 'timetable/css/scroll.css' %}" rel="stylesheet">

  <!--Iframe resizer-->



</head>

<body id="page-top">

  <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
    <a class="navbar-brand mr-1" href="{% url 'timetable:dashboard_home' %}"><div><img id="logoimg" src="{% static 'timetable/img/dblogo.png'%}" height="80px"></a>
    <!-- Navbar -->
    <div id="long_nav_side">
    <ul class="navbar-nav ml-auto ml-md-0">
      
      <li id="user_greet">Hello {{ username }}!</li>
      
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="icon_rep_med" src="{% static 'home/img/bell.png' %}">
          <span class="badge badge-danger">1</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
          <a class="dropdown-item notifier" href="#" aria-disabled="true">notif 1</a>
          <a class="dropdown-item notifier" href="#"  aria-disabled="true">notif 2</a>
          <a class="dropdown-item notifier" href="#"  aria-disabled="true">notif 3</a>
        </div>
      </li>
      
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="icon_rep_med" src="{% static 'home/img/user.png' %}">
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
        </div>
      </li>

    </ul>
  </div>
  </nav>

  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
      
      <li class="nav-item">
        <a class="nav-link" href="{% url 'timetable:dashboard_home' %}">
            <img class="icon_rep_med" src="{% static 'home/img/dash.png' %}">
          <span>Dashboard</span>
        </a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" >
            <img class="icon_rep_med" src="{% static 'home/img/activity.png' %}" >
          
            <span >Activity Center</span>
          <img class="icon_rep_small" id="down_arrow" src="{% static 'home/img/down.png' %}" >
        </a>
        <div class="dropdown-menu" aria-labelledby="pagesDropdown">
          <h6 class="dropdown-header">ACTIONS</h6>
          <a class="dropdown-item" href="{% url 'timetable:dashboard_tt' %}" >Timetable</a>
          <a class="dropdown-item" href="{% url 'timetable:dashboard_attend' %}" >Attendance Manager</a>
          <div class="dropdown-divider"></div>
          <h6 class="dropdown-header">CR TOOLS</h6>
          <a class="dropdown-item active" href="{% url 'crtools:crtools_tt' %}">Timetable Admin</a>
          <a class="dropdown-item" href="{% url 'crtools:crtools_rem' %}">Reminders Admin</a>
        </div>
      </li>
    </ul>

    <div id="content-wrapper">

      <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'timetable:dashboard_home' %}">Dashboard</a>
          </li>
          <li class="breadcrumb-item active">Timetable-Admin</li>
        </ol>

        <!-- Page Content -->
        <h1>Replace, Delete & Add Classes</h1>
        <hr>
        <div class="resp-container">
            <iframe class="resp-iframe" id="iframe_cr_rem" src ="{%  url 'crtools:cr_tt' %}" >
                Why don't you upgrade to a newer browser?
            </iframe>
          </div>
      </div>
      <!-- /.container-fluid -->

      <!-- Sticky Footer -->
      <footer class="sticky-footer">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Simul-HCI Assignment 2019</span>
          </div>
        </div>
      </footer>

    </div>
    <!-- /.content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
      <img class="icon_rep_med" src="{% static 'home/img/top.png' %}">
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'home:homepage' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'timetable/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'timetable/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'timetable/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'timetable/js/sb-admin.min.js' %}"></script>
  <script src="{% static 'timetable/js/iframe_changer.js' %}"></script>

</body>

</html>