simul/home/urls.py
from django.urls import path
from . import views

app_name="home"
urlpatterns = [
    # ex: /polls/
    path('', views.display_home, name='homepage'),
    path('login/',views.login_custom ,name='login'),
]

simul/simul/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('',include('home.urls')),
    path('dashboard/',include('timetable.urls')),
    path('crtools/',include('crtools.urls')),
    path('teacher/',include('teacher.urls')),
    path('admin/', admin.site.urls),
]

simul/teacher/urls.py
from django.urls import path
from . import views

app_name="teacher"
urlpatterns = [
    # ex: /polls/
    path('login/',views.teacher_login ,name='login'),
    path('dash/',views.teacher_dash,name="home"),
    path('add/',views.teacher_add,name="add"),
    path("attendance/",views.teacher_attendance,name="attendance")
]

simul/timetable/urls.py
from django.urls import path

from . import views

app_name="timetable"
urlpatterns = [
    # ex: /polls/
    path('', views.db_home_full, name='dashboard_home'),
    path('?p1?home/', views.db_home, name='db_home'),
    path('timetable/', views.db_tt_full, name='dashboard_tt'),
    path('?p2?tt/', views.db_tt, name='db_tt'),
    path('attendance/', views.db_attend_full, name='dashboard_attend'),
    path('?p3?att/', views.db_attend, name='db_attend'),    

]

simul/teacher/models.py
from django.db import models

class TeacherAcc(models.Model):
    name=models.CharField(max_length=40)
    username=models.CharField(max_length=20)
    password=models.CharField(max_length=10)
    
# Create your models here.

simul/teacher/views.py
from django.shortcuts import render,redirect
from .models import TeacherAcc
from django.urls import reverse
from urllib import request
from home.models import Student
from timetable.models import Course,Enrolled
import bluetooth
# Create your views here.

def teacher_login(request):
    request.session.flush()
    context={}
    if request.method=='POST':
        username=request.POST['login_email']
        password=request.POST['pwd_login']
        try:
            user=TeacherAcc.objects.get(username=username)
        except:
            context['errormessage']="This user is not registered"
            return render(request, 'teacher/teacher_login.html', context)
        
        if password!=user.password:
            context['errormessage']="Password doesn't match"
            return render(request, 'home/login.html', context)
        #response = db_home_full(request,context)
        #return response
        request.session['username']=user.name
        request.session['userid']=user.id
        return redirect(reverse('teacher:home'))
   
    return render(request,'teacher/teach_login.html',context)

def teacher_dash(request):
    username=request.session.get('username')
    userid=request.session.get('userid')
    if userid is None:
        return redirect(reverse('teacher:login'))
    context={
        'username':username,
    }
    return render(request,'teacher/teach_dash.html',context)

def teacher_add(request):
    username=request.session.get('username')
    userid=request.session.get('userid')
    # if userid is None:
    #     return redirect(reverse('teacher:login'))
    context={
        'username':username,
    }
    if request.method=="POST":
        if 'fstudent' in request.POST:
            try:
                user=Student.objects.get(rollno=int(request.POST['rno']))
                context['student_roll']=user.rollno
                context['student_name']=user.name
                context['student_sem']=user.semester
                context['student_dev_id']=user.dev_id
                context['found_student']=True
            except:
                context['error']=True
                return render(request,'teacher/teach_add.html',context)
        
        if 'updateid' in request.POST:
            user=Student.objects.get(rollno=int(request.POST['updateid']))  
            user.dev_id=request.POST['dev-id']
            user.save()
            context['student_roll']=user.rollno
            context['student_name']=user.name
            context['student_sem']=user.semester
            context['student_dev_id']=user.dev_id
            context['found_student']=True
            context['success']=True
    
    return render(request,'teacher/teach_add.html',context)

present_students=[]
course_cd=None
absent_students=[] 
def teacher_attendance(request):
    global present_students, absent_students,course_cd
    context={}
    username=request.session.get('username')
    #userid=request.session.get('userid')
    userid=1
    courses=Course.objects.filter(teacher=userid)
    context['courses']=courses
    
    if 'selcourse' in request.POST:
        context['att_success']=True
        
        course=Course.objects.get(course_code= request.POST['course_add_sel'])
        course.num_classes+=1
        course.save()
        course_cd=request.POST['course_add_sel']
        all_students=Enrolled.objects.filter(course_code= request.POST['course_add_sel'])
        
        nearby_devices = bluetooth.discover_devices(duration=4,lookup_names=True, flush_cache=True, lookup_class=False)
        
        for addr, name in nearby_devices:
            try:
                student_by_addr=Student.objects.get(dev_id=str(addr))
                present_students.append(student_by_addr)
            except:
                continue
        
        for student in all_students:
            if student.student_id not in present_students:
                absent_students.append(student.student_id)
        
        context['absentees']=absent_students
        
    if 'end_att' in request.POST:
        marked_present=request.POST.getlist('checks[]')
        course_code=course_cd
        for stu in marked_present:
            st=Student.objects.get(rollno=int(stu))
            present_students.append(st)
            absent_students.remove(st)
        print(absent_students)
        for stu in absent_students:
            print(stu.name)

            enr_up=Enrolled.objects.get(student_id=stu,course_code=course_code)
            print(enr_up)
            enr_up.classes_bunked+=1
            enr_up.official_classes_bunked+=1
            enr_up.save()
        context['att_complete']=True

    # if userid is None:
    #     return redirect(reverse('teacher:login'))
    return render(request,'teacher/teach_attendance.html',context)

simul/teacher/templates/teacher/teach_add.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <link rel="icon" type="image/ico" href="{% static 'home/img/fav.ico' %}"/>
  <style>
    @import url('https://fonts.googleapis.com/css?family=Open+Sans|Voltaire');
  </style>
  <title> Teacher Dashboard | Simul </title>

  <!-- Page level plugin CSS-->
  <link href="{% static 'timetable/vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'timetable/css/sb-admin.css' %}" rel="stylesheet">
  <link href="{% static 'timetable/css/scroll.css' %}" rel="stylesheet">

  <!--Iframe resizer-->



</head>

<body id="page-top">

  <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
    <a class="navbar-brand mr-1" href="{% url 'timetable:dashboard_home' %}"><div><img id="logoimg" src="{% static 'teacher/img/simulteach_logo.png'%}" height="80px"></a>
    <!-- Navbar -->
    <div id="long_nav_side">
    <ul class="navbar-nav ml-auto ml-md-0">
      
      <li id="user_greet">Hello {{ username }}!</li>
      
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="icon_rep_med" src="{% static 'home/img/bell.png' %}">
          <span class="badge badge-danger" hidden>1</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
          <a class="dropdown-item notifier" href="#" aria-disabled="true">notif 1</a>
          <a class="dropdown-item notifier" href="#"  aria-disabled="true">notif 2</a>
          <a class="dropdown-item notifier" href="#"  aria-disabled="true">notif 3</a>
        </div>
      </li>
      
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="icon_rep_med" src="{% static 'home/img/user.png' %}">
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
        </div>
      </li>

    </ul>
  </div>
  </nav>

  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
      
      <li class="nav-item">
        <a class="nav-link" href="{% url 'teacher:home' %}">
            <img class="icon_rep_med" src="{% static 'home/img/dash.png' %}">
          <span>Dashboard</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'teacher:add' %}">
          <span>Add Student Device</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'teacher:attendance' %}">
          <span>Take Attendance</span>
        </a>
      </li>
     
    </ul>

    <div id="content-wrapper">

      <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'timetable:dashboard_home' %}">Teacher Dashboard</a>
          </li>
          <li class="breadcrumb-item active">Add Device</li>
        </ol>

        <!-- Page Content -->
        <h1>Add or Edit a Student's registered device id</h1>
        <hr>
            <h4>Warning: Ask the student to show you the MAC id of their new device before you update</h4>
            <br>
            <form method="POST">
            {% csrf_token %}
            <label>Student Roll Number:&nbsp;&nbsp;&nbsp;&nbsp; </label><input type="number" name="rno">&nbsp;&nbsp;&nbsp;&nbsp;<button name="fstudent">Find Student</button>
            <hr>
            {% if found_student %}
            <label>Student Name: &nbsp;&nbsp;&nbsp;&nbsp;</label><input type="text" disabled value= {{ student_name }}>
            <br>
            <label>Student Roll Number: &nbsp;&nbsp;&nbsp;&nbsp;</label><input type="number" name="sroll" disabled  value={{ student_roll }}>
            <br>
            <label>Student Semester: &nbsp;&nbsp;&nbsp;&nbsp;</label><input type="number" disabled value={{ student_sem }}>
            <br>
            <label>Device ID: &nbsp;&nbsp;&nbsp;&nbsp;</label><input type="text" name="dev-id" value={{ student_dev_id }} >&nbsp;&nbsp;&nbsp;&nbsp;<button type="submit" name="updateid" value={{ student_roll }}>Update ID</button>
            <hr>
            {% endif %}
          
            {% if error %}
            <p class="text-danger">Student with this id is not registered</p>
            {% endif %}
            {% if success %}
            <p class="text-success">Student device-id updated successfully</p>
            {% endif %}
            </form>
      </div>
      <!-- /.container-fluid -->

      <!-- Sticky Footer -->
      <footer class="sticky-footer">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Simul-HCI Assignment 2019</span>
          </div>
        </div>
      </footer>

    </div>
    <!-- /.content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
      <img class="icon_rep_med" src="{% static 'home/img/top.png' %}">
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'home:homepage' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'timetable/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'timetable/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'timetable/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'timetable/js/sb-admin.min.js' %}"></script>
  <script src="{% static 'timetable/js/iframe_changer.js' %}"></script>

</body>

</html>

simul/teacher/templates/teacher/teach_attendance.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <link rel="icon" type="image/ico" href="{% static 'home/img/fav.ico' %}"/>
  <style>
    @import url('https://fonts.googleapis.com/css?family=Open+Sans|Voltaire');
  </style>
  <title> Teacher Dashboard | Simul </title>

  <!-- Page level plugin CSS-->
  <link href="{% static 'timetable/vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'timetable/css/sb-admin.css' %}" rel="stylesheet">
  <link href="{% static 'timetable/css/scroll.css' %}" rel="stylesheet">
  <link href="{% static 'teacher/css/t_att.css' %}" rel="stylesheet">

  <!--Iframe resizer-->



</head>

<body id="page-top">

  <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
    <a class="navbar-brand mr-1" href="{% url 'timetable:dashboard_home' %}"><div><img id="logoimg" src="{% static 'teacher/img/simulteach_logo.png'%}" height="80px"></a>
    <!-- Navbar -->
    <div id="long_nav_side">
    <ul class="navbar-nav ml-auto ml-md-0">
      
      <li id="user_greet">Hello {{ username }}!</li>
      
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="icon_rep_med" src="{% static 'home/img/bell.png' %}">
          <span class="badge badge-danger" hidden>1</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
          <a class="dropdown-item notifier" href="#" aria-disabled="true">notif 1</a>
          <a class="dropdown-item notifier" href="#"  aria-disabled="true">notif 2</a>
          <a class="dropdown-item notifier" href="#"  aria-disabled="true">notif 3</a>
        </div>
      </li>
      
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="icon_rep_med" src="{% static 'home/img/user.png' %}">
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
        </div>
      </li>

    </ul>
  </div>
  </nav>

  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
      
      <li class="nav-item">
        <a class="nav-link" href="{% url 'teacher:home' %}">
            <img class="icon_rep_med" src="{% static 'home/img/dash.png' %}">
          <span>Dashboard</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'teacher:add' %}">
          <span>Add Student Device</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'teacher:attendance' %}">
          <span>Take Attendance</span>
        </a>
      </li>
     
    </ul>

    <div id="content-wrapper">

      <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'timetable:dashboard_home' %}">Teacher Dashboard</a>
          </li>
          <li class="breadcrumb-item active">Home</li>
        </ol>

        <!-- Page Content -->
        <h1>Take Attendance</h1>
        <form method="POST">
        {% csrf_token %}
        <hr>
            <label>Select Course</label>
                <select name="course_add_sel">
                    {% for course in courses %}
                    <option value= {{ course.course_code }}> {{ course.course_name }}</option>
                    {% endfor %}
                </select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <button name="selcourse">Select Course</button>

        <hr>
        {% if att_success %}
        <p class="text-success">Attendance scan successful. Confirm Absentees: </p>
        <h3>Absentees: </h3>
        <table class="table-bordered" id="att_table">
          <thead>
            <tr>
              <td>Student Name</td>
              <td>Student Roll Number</td>
              <td>Device ID</td>
              <td>Mark Present</td>
            </tr>
          </thead>
          {% for absentee in absentees %}
          <tr>
            <td>{{ absentee.name }}</td>
            <td>{{ absentee.rollno }}</td>
            <td>{{ absentee.dev_id }}</td>
            <td><input type="checkbox" name="checks[]" value={{ absentee.rollno }}></td>
          </tr>
          {% endfor %}
        </table>
        <br>
      
      <button name="end_att">Confirm Attendance</button>
      <br>
      <hr>
      {% endif %}
      {% if att_complete%}
      <h5 class="text-success"> Attendance logged successfully </h5>
      {% endif %}
      </form>
      </div>
      <!-- /.container-fluid -->

      <!-- Sticky Footer -->
      <footer class="sticky-footer">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Simul-HCI Assignment 2019</span>
          </div>
        </div>
      </footer>

    </div>
    <!-- /.content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
      <img class="icon_rep_med" src="{% static 'home/img/top.png' %}">
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'home:homepage' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'timetable/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'timetable/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'timetable/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'timetable/js/sb-admin.min.js' %}"></script>
  <script src="{% static 'timetable/js/iframe_changer.js' %}"></script>

</body>

</html>

simul/teacher/templates/teacher/teach_dash.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <link rel="icon" type="image/ico" href="{% static 'home/img/fav.ico' %}"/>
  <style>
    @import url('https://fonts.googleapis.com/css?family=Open+Sans|Voltaire');
  </style>
  <title> Teacher Dashboard | Simul </title>

  <!-- Page level plugin CSS-->
  <link href="{% static 'timetable/vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'timetable/css/sb-admin.css' %}" rel="stylesheet">
  <link href="{% static 'timetable/css/scroll.css' %}" rel="stylesheet">

  <!--Iframe resizer-->



</head>

<body id="page-top">

  <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
    <a class="navbar-brand mr-1" href="{% url 'timetable:dashboard_home' %}"><div><img id="logoimg" src="{% static 'teacher/img/simulteach_logo.png'%}" height="80px"></a>
    <!-- Navbar -->
    <div id="long_nav_side">
    <ul class="navbar-nav ml-auto ml-md-0">
      
      <li id="user_greet">Hello {{ username }}!</li>
      
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="icon_rep_med" src="{% static 'home/img/bell.png' %}">
          <span class="badge badge-danger" hidden>1</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
          <a class="dropdown-item notifier" href="#" aria-disabled="true">notif 1</a>
          <a class="dropdown-item notifier" href="#"  aria-disabled="true">notif 2</a>
          <a class="dropdown-item notifier" href="#"  aria-disabled="true">notif 3</a>
        </div>
      </li>
      
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="icon_rep_med" src="{% static 'home/img/user.png' %}">
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
        </div>
      </li>

    </ul>
  </div>
  </nav>

  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
      
      <li class="nav-item">
        <a class="nav-link" href="{% url 'teacher:home' %}">
            <img class="icon_rep_med" src="{% static 'home/img/dash.png' %}">
          <span>Dashboard</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'teacher:add' %}">
          <span>Add Student Device</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'teacher:attendance' %}">
          <span>Take Attendance</span>
        </a>
      </li>
     
    </ul>

    <div id="content-wrapper">

      <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'timetable:dashboard_home' %}">Teacher Dashboard</a>
          </li>
          <li class="breadcrumb-item active">Home</li>
        </ol>

        <!-- Page Content -->
        <h1>Welcome to SimulTeach!</h1>
        <hr>
            <h2>The supplement which makes attendance easier</h2>

            <p>Introducing our revolutionary attendance taking system. Take attendance in roughly 2 minutes of your time with an accuracy like never before!</p>
      </div>
      <!-- /.container-fluid -->

      <!-- Sticky Footer -->
      <footer class="sticky-footer">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Simul-HCI Assignment 2019</span>
          </div>
        </div>
      </footer>

    </div>
    <!-- /.content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
      <img class="icon_rep_med" src="{% static 'home/img/top.png' %}">
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'home:homepage' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'timetable/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'timetable/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'timetable/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'timetable/js/sb-admin.min.js' %}"></script>
  <script src="{% static 'timetable/js/iframe_changer.js' %}"></script>

</body>

</html>

simul/teacher/templates/teacher/teach_login.html
<!DOCTYPE html>
<html>
    {% load static %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Teacher Login | Simul</title>
  <link rel="icon" type="image/ico" href="{% static 'home/img/fav.ico' %}"/>
 
  <style>
    @import url('https://fonts.googleapis.com/css?family=Open+Sans|Voltaire');
  </style>

<link rel="stylesheet" type="text/css" href="{% static 'home/css/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'home/css/style2.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'home/css/bootstrap.min.css' %}">
  <link href="{% static 'timetable/css/scroll.css' %}" rel="stylesheet">

  <script src="{% static 'home/js/jquery.min.js' %}"></script>
  <script src="{% static 'home/js/bootstrap.bundle.min.js' %}"></script>


</head>
<body >
    <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                <div><a href="{% url 'home:homepage' %}"><img id="main-logo" src="{% static 'teacher/img/simulteach_blk.png' %}" height="90px"></a>
                </div>
            </div>
            </div>
            </nav>  

          
    <table id="login_table">
        <tr>
            <td id="image_col">
                <img id="login_img" src="{% static 'home/img/fav.png' %}">
            </td>
            <td id="form_col">
                <div class="container">
                        <div class="row">
                            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                            <div class="card card-signin my-5">
                                <div class="card-body">
                                <h5 id="error_mess" class="card-title text-center"> {{ errormessage }} </h5> 
                                <h5 class="card-title text-center">Sign In</h5>
                                <form class="form-signin" method="POST">
                                    {% csrf_token %}
                                    <div class="form-label-group">
                                    <input type="email" id="inputEmail" class="form-control" placeholder="Email address" name="login_email" required autofocus>
                                    <label for="inputEmail">Email address</label>
                                    </div>
                    
                                    <div class="form-label-group">
                                    <input type="password" id="inputPassword" class="form-control" placeholder="Password" name="pwd_login" required>
                                    <label for="inputPassword">Password </label>
                                    </div>
                    
                                    <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Sign in</button>
                                    <hr class="my-4">
                                </form>
                                </div>
                            </div>
                            </div>
                        </div>
                        </div>
            </td>
        </tr>
        </table>
  </body>
</html>