simul/crtools/urls.py
from django.urls import path

from . import views

app_name="crtools"
urlpatterns = [
    # ex: /polls/
    path('timetable/', views.tt_admin_full, name='crtools_tt'),
    path('?p4?admintt/', views.tt_admin, name='cr_tt'),
    path('?p5?adminrem/', views.rem_admin, name='cr_rem'),
    path('reminders/', views.rem_admin_full, name='crtools_rem'),
    
]

simul/home/urls.py
from django.urls import path
from . import views

app_name="home"
urlpatterns = [
    # ex: /polls/
    path('', views.display_home, name='homepage'),
    path('login/',views.login_custom ,name='login'),
]

simul/simul/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('',include('home.urls')),
    path('dashboard/',include('timetable.urls')),
    path('crtools/',include('crtools.urls')),
    path('teacher/',include('teacher.urls')),
    path('admin/', admin.site.urls),
]

simul/timetable/urls.py
from django.urls import path

from . import views

app_name="timetable"
urlpatterns = [
    # ex: /polls/
    path('', views.db_home_full, name='dashboard_home'),
    path('?p1?home/', views.db_home, name='db_home'),
    path('timetable/', views.db_tt_full, name='dashboard_tt'),
    path('?p2?tt/', views.db_tt, name='db_tt'),
    path('attendance/', views.db_attend_full, name='dashboard_attend'),
    path('?p3?att/', views.db_attend, name='db_attend'),    

]

simul/home/models.py
from django.db import models

class Student(models.Model):

    name=models.CharField(max_length=40)
    username=models.CharField(max_length=20)
    password=models.CharField(max_length=10)
    rollno=models.IntegerField()
    rollno.primary_key=True
    classid=models.CharField(max_length=10)
    semester=models.IntegerField()
    last_online=models.DateField(auto_now=True)
    cr=models.BooleanField()
    dev_id=models.CharField(max_length=40)

# Create your models here.

simul/timetable/models.py
from django.db import models
from home.models import Student
from teacher.models import TeacherAcc

class Course(models.Model):
    course_name=models.CharField(max_length=40)
    class_id=models.CharField(max_length=10)
    course_code=models.CharField(max_length=10)
    course_code.primary_key=True
    course_semester=models.IntegerField(default=0)
    course_credits=models.IntegerField(default=0)
    lectures=models.IntegerField(default=0)
    labs=models.IntegerField(default=0)
    num_classes=models.IntegerField(default=1)
    teacher=models.ForeignKey(TeacherAcc,on_delete=models.SET(0))

class Enrolled(models.Model):
    student_id=models.ForeignKey(Student,on_delete=models.CASCADE)
    course_code=models.ForeignKey(Course,on_delete=models.CASCADE)
    classes_bunked=models.IntegerField(default=0)
    bunk_percentage=models.FloatField(default=0)
    official_classes_bunked=models.IntegerField(default=0)

class TTFormat(models.Model):
    course_code=models.ForeignKey(Course,on_delete=models.CASCADE)
    start_hour=models.IntegerField(default=0)
    day=models.IntegerField(default=0)
    lab_hour=models.BooleanField(default=False)


# Create your models here.

simul/home/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Student
from timetable.views import db_home_full
from urllib import request
import datetime
import calendar

# Create your views here.

def display_home(request):
    request.session.delete()
    context={}
    return render(request, 'home/index.html', context)

def login_custom(request):
    request.session.flush()
    if request.method=='POST':
        context={}
        username=request.POST['login_email']
        password=request.POST['pwd_login']
        try:
            user=Student.objects.get(username=username)
        except:
            context['errormessage']="This user is not registered"
            return render(request, 'home/login.html', context)
        
        if password!=user.password:
            context['errormessage']="Password doesn't match"
            return render(request, 'home/login.html', context)
        #response = db_home_full(request,context)
        #return response
        today=datetime.datetime.now()
        request.session['username']=user.name
        request.session['userid']=user.rollno
        request.session['sem']=user.semester
        request.session['day']=today.weekday()+1
        request.session['date']=today.strftime(" %d-%m-%y")
        request.session['weekday']=calendar.day_name[today.weekday()]
        return redirect(reverse('timetable:dashboard_home'))
    else:
        context={}
        return render(request, 'home/login.html', context)

simul/timetable/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
import datetime
from home.models import Student
from .models import TTFormat,Course,Enrolled
from crtools.models import Reminder,TTChange
# Create your views here.

# HOMEPAGE


def db_home_full(request):
    username=request.session.get('username')
    userid=request.session.get('userid')
    if userid is None:
        return redirect(reverse('home:homepage'))
    context={
        'username':username,
    }
    return render(request, 'timetable/home_full.html',context)

def db_home(request):
    username=request.session.get('username')
    userid=request.session.get('userid')
    if userid is None:
        return redirect(reverse('home:homepage'))
    context={}
    return render(request, 'timetable/home.html', context)



#TIMETABLE

def db_tt_full(request):
    #get the required object - user
    #check for notifications and load
    #
    
    username=request.session.get('username')
    userid=request.session.get('userid')
    if userid is None:
        return redirect(reverse('home:homepage'))
    context={
        'username':username,
    }
    return render(request, 'timetable/timetable_full.html',context)

def db_tt(request):
    userid=request.session.get('userid')
    if userid is None:
        return redirect(reverse('home:homepage'))
    if request.method=="POST":
        context={}
        return render(request, 'timetable/attendance.html', context)

    weekday_today=request.session.get('day')
    
    original_tt=TTFormat.objects.filter(day=weekday_today).order_by('start_hour')
    changes_tt=TTChange.objects.filter(date=datetime.datetime.now().strftime("%Y-%m-%d")).order_by('start_hour','-date')
    

    merged_tt=[]
    for k in range(1,9):
        org=None
        ch=None
        for o in original_tt:
            if o.start_hour==k:
                org=o
                break
        for c in changes_tt:
            if c.start_hour==k:
                ch=c
                break
        if org and ch :
            if not ch.deleted:
                merged_tt.append(ch)
        if org and not ch:
            merged_tt.append(org)
        if ch and not org:
            merged_tt.append(ch)
    merged_tt=list(merged_tt)
    today=datetime.datetime.now().date().strftime('%Y-%m-%d')
    reminders=Reminder.objects.filter(set_date=today)
    
    context={
        'reminders':reminders,
        'classes_list':merged_tt,
        'day':request.session.get('weekday'),
        'date':request.session.get('date'),    
    }
    return render(request, 'timetable/timetable.html', context)


# ATTENDANCE
def db_attend_full(request):
    #get the required object - user
    #check for notifications and load
    #
    
    username=request.session.get('username')
    userid=request.session.get('userid')
    if userid is None:
        return redirect(reverse('home:homepage'))
    context={
        'username':username,
    }
    return render(request, 'timetable/attendance_full.html',context)


def db_attend(request):
    username=request.session.get('username')
    userid=request.session.get('userid')
    if userid is None:
        return redirect(reverse('home:homepage'))
    student=Student.objects.get(rollno=userid)
    courses=Enrolled.objects.filter(student_id=userid)

    if request.method=='POST':
        if 'bunk' in request.POST:
            course_changed=Enrolled.objects.get(course_code=request.POST['bunk'],student_id=student)
            if course_changed.classes_bunked<course_changed.course_code.num_classes:
                course_changed.classes_bunked+=1
            course_changed.save()
        else:
            course_changed=Enrolled.objects.get(course_code=request.POST['unbunk'],student_id=student)
            if course_changed.classes_bunked>0:
                course_changed.classes_bunked-=1
            course_changed.save()
    
    for course in courses:
        course.bunk_percentage=((course.course_code.num_classes-course.official_classes_bunked)/course.course_code.num_classes)*100.0
        course.save()
    context={
        'username':username,
        'courses':courses,
    }
    return render(request, 'timetable/attendance.html', context)

simul/timetable/templates/timetable/attendance.html
{% load static %}
<style>
        @import url('https://fonts.googleapis.com/css?family=Open+Sans|Voltaire');
</style>

<link href="{% static 'timetable/css/subscroll.css' %}" rel="stylesheet">
<link href="{% static 'timetable/css/iframe_style.css' %}" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'home/css/bootstrap.min.css' %}">

<body style="background-image: url({% static 'home/img/fav.png' %});">
   <table id="attendance_table">
        {% for course in courses %}
        <tr>
           
                <td>
                 {{course.course_code.course_name}}<br>
                 [ {{course.course_code.course_code}} ]
                 
                </td>
                <td>
                Classes Bunked : {{ course.official_classes_bunked }}
                <hr>
                Total Classes: {{ course.course_code.num_classes }}
                <hr>
                </td>
                <td>
                <h4> {{ course.bunk_percentage }} % </h4><br>
                <form method="POST">
                {% csrf_token %}
                    <button id="bunk" name="bunk" value= {{ course.course_code.course_code }}>Bunk Class</button>
                    <button id="unbunk" name="unbunk" value= {{ course.course_code.course_code}}>Un-Bunk Class</button>
                </form>
                </td>
        </tr>
        {% endfor %}
        
    
   </table>
</body>

simul/timetable/templates/timetable/attendance_full.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <link rel="icon" type="image/ico" href="{% static 'home/img/fav.ico' %}"/>
  <style>
    @import url('https://fonts.googleapis.com/css?family=Open+Sans|Voltaire');
  </style>
  <title> Dashboard | Simul </title>

  <!-- Page level plugin CSS-->
  <link href="{% static 'timetable/vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'timetable/css/sb-admin.css' %}" rel="stylesheet">
  <link href="{% static 'timetable/css/scroll.css' %}" rel="stylesheet">

  <!--Iframe resizer-->



</head>

<body id="page-top">

  <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
    <a class="navbar-brand mr-1" href="{% url 'timetable:dashboard_home' %}"><div><img id="logoimg" src="{% static 'timetable/img/dblogo.png'%}" height="80px"></a>
    <!-- Navbar -->
    <div id="long_nav_side">
    <ul class="navbar-nav ml-auto ml-md-0">
      
      <li id="user_greet">Hello {{ username }}!</li>
      
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="icon_rep_med" src="{% static 'home/img/bell.png' %}">
          <span class="badge badge-danger">1</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
          <a class="dropdown-item notifier" href="#" aria-disabled="true">notif 1</a>
          <a class="dropdown-item notifier" href="#"  aria-disabled="true">notif 2</a>
          <a class="dropdown-item notifier" href="#"  aria-disabled="true">notif 3</a>
        </div>
      </li>
      
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="icon_rep_med" src="{% static 'home/img/user.png' %}">
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
        </div>
      </li>

    </ul>
  </div>
  </nav>

  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
      
      <li class="nav-item">
        <a class="nav-link" href="{% url 'timetable:dashboard_home' %}">
            <img class="icon_rep_med" src="{% static 'home/img/dash.png' %}">
          <span>Dashboard</span>
        </a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" >
            <img class="icon_rep_med" src="{% static 'home/img/activity.png' %}" >
          
            <span >Activity Center</span>
          <img class="icon_rep_small" id="down_arrow" src="{% static 'home/img/down.png' %}" >
        
        </a>
        <div class="dropdown-menu" aria-labelledby="pagesDropdown">
          <h6 class="dropdown-header">ACTIONS</h6>
          <a class="dropdown-item" href="{% url 'timetable:dashboard_tt' %}" >Timetable</a>
          <a class="dropdown-item active" href="{% url 'timetable:dashboard_attend' %}" >Attendance Manager</a>
          <div class="dropdown-divider"></div>
          <h6 class="dropdown-header">CR TOOLS</h6>
          <a class="dropdown-item" href="{% url 'crtools:crtools_tt' %}">Timetable Admin</a>
          <a class="dropdown-item" href="{% url 'crtools:crtools_rem' %}">Reminders Admin</a>
        </div>
      </li>
    </ul>

    <div id="content-wrapper">

      <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'timetable:dashboard_home' %}">Dashboard</a>
          </li>
          <li class="breadcrumb-item active">Attendance</li>
        </ol>

        <!-- Page Content -->
        <h1>Attendance Status</h1>
        <hr>
        <div class="resp-container">
            <iframe class="resp-iframe" id="iframe_att" src ="{%  url 'timetable:db_attend' %}" >
                Why don't you upgrade to a newer browser?
            </iframe>
          </div>
      </div>
      <!-- /.container-fluid -->

      <!-- Sticky Footer -->
      <footer class="sticky-footer">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Simul-HCI Assignment 2019</span>
          </div>
        </div>
      </footer>

    </div>
    <!-- /.content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
      <img class="icon_rep_med" src="{% static 'home/img/top.png' %}">
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'home:homepage' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'timetable/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'timetable/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'timetable/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'timetable/js/sb-admin.min.js' %}"></script>
  <script src="{% static 'timetable/js/iframe_changer.js' %}"></script>

</body>

</html>

simul/timetable/templates/timetable/home.html
{% load static %}
<style>
        @import url('https://fonts.googleapis.com/css?family=Open+Sans|Voltaire');
</style>

<link href="{% static 'timetable/css/subscroll.css' %}" rel="stylesheet">
<link href="{% static 'timetable/css/iframe_style.css' %}" rel="stylesheet">
<body style="background-image: url({% static 'home/img/fav.png' %});">
        <p>
                Here's a quick look at what everything does:
                <ul>
                    <li><b>Dashboard:</b> This page you're looking at right now!</li>
                    <li><b>Activity Center:</b>
                        <ul>
                            <li><b>Timetable:</b> A quick view of this weeks timetable, with reminders</li>
                            <li><b>Polls:</b> Vote on polls set by your CR</li>
                            <li><b>Attendance Manager:</b> Check how close you are to an FA</li>
                            <li><b>CR Tools:</b> A CR's saving grace. Manage all the above functions for your classmates!</li>
                        </ul>
                    </li>
                </ul>
            </p>
</body>

simul/timetable/templates/timetable/home_full.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <link rel="icon" type="image/ico" href="{% static 'home/img/fav.ico' %}"/>
  <style>
    @import url('https://fonts.googleapis.com/css?family=Open+Sans|Voltaire');
  </style>
  <title> Dashboard | Simul </title>

  <!-- Page level plugin CSS-->
  <link href="{% static 'timetable/vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'timetable/css/sb-admin.css' %}" rel="stylesheet">
  <link href="{% static 'timetable/css/scroll.css' %}" rel="stylesheet">

  <!--Iframe resizer-->



</head>

<body id="page-top">

  <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
    <a class="navbar-brand mr-1" href="{% url 'timetable:dashboard_home' %}"><div><img id="logoimg" src="{% static 'timetable/img/dblogo.png'%}" height="80px"></a>
    <!-- Navbar -->
    <div id="long_nav_side">
    <ul class="navbar-nav ml-auto ml-md-0">
      
      <li id="user_greet">Hello {{ username }}!</li>
      
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="icon_rep_med" src="{% static 'home/img/bell.png' %}">
          <span class="badge badge-danger" hidden>1</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
          <a class="dropdown-item notifier" href="#" aria-disabled="true">notif 1</a>
          <a class="dropdown-item notifier" href="#"  aria-disabled="true">notif 2</a>
          <a class="dropdown-item notifier" href="#"  aria-disabled="true">notif 3</a>
        </div>
      </li>
      
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="icon_rep_med" src="{% static 'home/img/user.png' %}">
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
        </div>
      </li>

    </ul>
  </div>
  </nav>

  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
      
      <li class="nav-item">
        <a class="nav-link" href="{% url 'timetable:dashboard_home' %}">
            <img class="icon_rep_med" src="{% static 'home/img/dash.png' %}">
          <span>Dashboard</span>
        </a>
      </li>

      <li class="nav-item dropdown">
         
        <a class="nav-link dropdown-toggle" href="" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" onclick="arrow_switch();">
            <img class="icon_rep_med" src="{% static 'home/img/activity.png' %}" >
          
            <span >Activity Center</span>
          <img class="icon_rep_small" id="down_arrow" src="{% static 'home/img/down.png' %}" style="visibility:visible;">
          <img class="icon_rep_small" id="up_arrow" src="{% static 'home/img/top.png' %}" style="visibility:hidden;">
        </a>
        <div class="dropdown-menu" aria-labelledby="pagesDropdown">
          <h6 class="dropdown-header">ACTIONS</h6>
          <a class="dropdown-item" href="{% url 'timetable:dashboard_tt' %}" >Timetable</a>
          <a class="dropdown-item" href="{% url 'timetable:dashboard_attend' %}" >Attendance Manager</a>
          <div class="dropdown-divider"></div>
          <h6 class="dropdown-header">CR TOOLS</h6>
          <a class="dropdown-item" href="{% url 'crtools:crtools_tt' %}">Timetable Admin</a>
          <a class="dropdown-item" href="{% url 'crtools:crtools_rem' %}">Reminders Admin</a>
        </div>
      </li>
    </ul>

    <div id="content-wrapper">

      <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'timetable:dashboard_home' %}">Dashboard</a>
          </li>
          <li class="breadcrumb-item active">Home</li>
        </ol>

        <!-- Page Content -->
        <h1>Welcome to Simul!</h1>
        <hr>
        <div class="resp-container">
            <iframe class="resp-iframe" id="iframe_home" src ="{%  url 'timetable:db_home' %}">
                Why don't you upgrade to a newer browser?
            </iframe>
          </div>
      </div>
      <!-- /.container-fluid -->

      <!-- Sticky Footer -->
      <footer class="sticky-footer">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Simul-HCI Assignment 2019</span>
          </div>
        </div>
      </footer>

    </div>
    <!-- /.content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
      <img class="icon_rep_med" src="{% static 'home/img/top.png' %}">
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'home:homepage' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'timetable/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'timetable/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'timetable/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'timetable/js/sb-admin.min.js' %}"></script>
  <script src="{% static 'timetable/js/iframe_changer.js' %}"></script>

</body>

</html>

simul/timetable/templates/timetable/timetable.html
{% load static %}
<style>
        @import url('https://fonts.googleapis.com/css?family=Open+Sans|Voltaire');
</style>

<link href="{% static 'timetable/css/subscroll.css' %}" rel="stylesheet">
<link href="{% static 'timetable/css/iframe_style.css' %}" rel="stylesheet">

<body style="background-image: url({% static 'home/img/fav.png' %});">
    <h3> {{ day }} : {{ date }}</h3>
    <br><hr><br>
    <table id="tt_main">
            <tr>
                {% for class in classes_list %}
                {% if class.lab_hour %}
                <td><div class="tt_block_lab">
                                <br>
                                {{ class.course_code.course_code }}
                                <br>
                                {{ class.course_code.course_name }} LAB
                                <br>
                                Start hour: {{ class.start_hour }}
                            </div></td>
                {% else %}
                <td><div class="tt_block_lec">
                                <br>
                                {{ class.course_code.course_code }}
                                <br>
                                {{ class.course_code.course_name }} LEC
                                <br>
                                Start hour: {{ class.start_hour }}
                            </div></td>
                {% endif %}
                {% endfor %}
            </tr>
        </table>
    <br>
    <h2>Reminders:</h2>
    <div id="reminder_div">
            {% for rem in reminders %}
            <div class="rem_div">
                    {{ rem.reminder_text }} 
                    <hr>
                </div>
            {% endfor %}
    </div>
    
    <a href="{% url 'timetable:db_attend' %}">
    <button id="bunk_button" type="button">Manage Class Attendance</button>
    </a>
</body>